name: coverage

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6
        with:
          node-version: 20

      - run: npm ci

      - run: npx vitest run --coverage

      - name: Generate simplified coverage badge JSON
        run: |
          mkdir -p public

          pct=$(jq '.total.statements.pct' coverage/coverage-summary.json)

          pct_int=$(printf "%.0f" $pct)

          if (( pct_int < 60 )); then
            color="red"
          elif (( pct_int < 80 )); then
            color="yellow"
          else
            color="brightgreen"
          fi

          echo "{
            \"schemaVersion\": 1,
            \"label\": \"coverage\",
            \"message\": \"${pct_int}%\",
            \"color\": \"${color}\"
          }" > public/coverage.json

      - name: Upload artifact for Pages
        uses: actions/upload-artifact@v5
        with:
          name: github-pages
          path: public
